"""
Django settings for sbomify project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import asyncio
import logging
import os
import sys
import warnings
from pathlib import Path
from typing import Any
from urllib.parse import urlparse, urlunparse

import dj_database_url
import redis
import sentry_sdk
from django.contrib import messages
from dotenv import find_dotenv, load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.dramatiq import DramatiqIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

from sbomify.apps.plugins.utils import get_sbomify_version
from sbomify.logging_filters import is_benign_shielded_future_error
from sbomify.sentry_config import resolve_environment, should_warn_missing_dsn

ENV_FILE = find_dotenv()
if ENV_FILE:
    load_dotenv(ENV_FILE)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Define IN_DOCKER early
IN_DOCKER = bool(int(os.environ["AM_I_IN_DOCKER_CONTAINER"])) if "AM_I_IN_DOCKER_CONTAINER" in os.environ else False

API_VERSION = "v1"

# This is used for the SBOM analysis results cache
OSV_SCANNER_RAW_RESULT_EXPIRY_SECONDS = int(os.environ.get("OSV_SCANNER_RAW_RESULT_EXPIRY_SECONDS", 7 * 24 * 3600))

# OSV Scanner subprocess timeout in seconds (default: 5 minutes, less than Dramatiq's 6-minute time limit)
OSV_SCANNER_TIMEOUT_SECONDS = int(os.environ.get("OSV_SCANNER_TIMEOUT_SECONDS", 300))

# Vulnerability scanning cache TTL in seconds (default: 1 hour)
VULNERABILITY_SCAN_CACHE_TTL = int(os.environ.get("VULNERABILITY_SCAN_CACHE_TTL", 3600))

# TEA API response cache TTL in seconds (default: 1 hour). Set to 0 to disable.
TEA_CACHE_TTL: int = int(os.environ.get("TEA_CACHE_TTL", "3600"))

# Dependency Track processing delay in seconds (default: 5 seconds)
# Time to wait after SBOM upload before retrieving results to allow DT to process
DT_PROCESSING_DELAY_SECONDS = int(os.environ.get("DT_PROCESSING_DELAY_SECONDS", 5))

# Payment failure grace period in days before account is restricted
PAYMENT_GRACE_PERIOD_DAYS = int(os.environ.get("PAYMENT_GRACE_PERIOD_DAYS", 3))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "")

# Signing salt for signed URLs (should be unique per installation)
SIGNED_URL_SALT = os.environ.get("SIGNED_URL_SALT", "django-insecure-signed-url-salt-CHANGE-ME!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Local development mode (separate from DEBUG for security)
LOCAL_DEV = os.environ.get("LOCAL_DEV", "False").lower() == "true"


def _env_bool(value: str | None, default: bool) -> bool:
    if value is None:
        return default
    return value.lower() in ("true", "1", "yes")


# Request timing logging is disabled by default to avoid performance impact
# Enable explicitly when needed for profiling (e.g., REQUEST_TIMING_LOGGING_ENABLED=true)
REQUEST_TIMING_LOGGING_ENABLED = _env_bool(os.environ.get("REQUEST_TIMING_LOGGING_ENABLED"), default=False)
PENDING_INVITATIONS_CACHE_TTL = int(os.environ.get("PENDING_INVITATIONS_CACHE_TTL", "60"))

# ALLOWED_HOSTS set to wildcard - actual host validation done in middleware
# Django 4.0+ requires ALLOWED_HOSTS to be a plain list/tuple
# Use DynamicHostValidationMiddleware for dynamic custom domain validation
ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = "core.User"

# Make Django work behind reverse proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Networks whose requests are allowed to set the client IP via the X-Real-IP
# header (see core.utils.get_client_ip). Only honour that header when the direct
# peer (REMOTE_ADDR) is a trusted reverse proxy; otherwise a client reaching
# Django directly could spoof its IP and defeat per-IP rate limiting.
#
# The default trusts loopback + RFC1918 ranges, which cover the Caddy sidecar in
# the default Docker topology (where the app is NOT directly reachable — the
# backend port is unpublished). If Django can be reached directly from any other
# private segment (shared cluster, corp VPN), narrow this to the actual
# reverse-proxy address(es) via the TRUSTED_PROXIES env var so those clients
# cannot spoof X-Real-IP.
TRUSTED_PROXIES = [
    cidr.strip()
    for cidr in os.environ.get(
        "TRUSTED_PROXIES",
        "127.0.0.0/8,::1/128,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
    ).split(",")
    if cidr.strip()
]

# Allow larger request bodies for OSCAL catalog imports (default is 2.5 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 MB

# Prevent browsers from MIME-sniffing responses away from their declared
# Content-Type — defense-in-depth for user-uploaded artifact downloads.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Content-Security-Policy (see ContentSecurityPolicyMiddleware). Shipped in
# Report-Only mode by default so violations can be observed before enforcement;
# set CSP_ENFORCE=True once the reports are clean. The app relies on inline
# Alpine.js expressions (needs 'unsafe-inline'/'unsafe-eval'), Stripe.js and
# websockets, so the policy stays permissive on scripts while locking down
# object-src, base-uri and plugin embedding.
#
# Report-Only violations are only delivered somewhere if CSP_REPORT_URI points
# at a collector endpoint (e.g. Sentry's CSP ingest URL); without it, browsers
# just log violations to their console. Set it to make the rollout actionable.
CSP_ENFORCE = _env_bool(os.environ.get("CSP_ENFORCE"), default=False)
CSP_REPORT_URI = os.environ.get("CSP_REPORT_URI", "")
CONTENT_SECURITY_POLICY = os.environ.get(
    "CONTENT_SECURITY_POLICY",
    "; ".join(
        [
            "default-src 'self'",
            "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com",
            "style-src 'self' 'unsafe-inline'",
            "img-src 'self' data: blob: https:",
            "font-src 'self' data:",
            "connect-src 'self' https: wss: ws:",
            "frame-src 'self' https://js.stripe.com https://hooks.stripe.com",
            "frame-ancestors 'self'",
            "base-uri 'self'",
            "object-src 'none'",
            "worker-src 'self' blob:",
        ]
    ),
)

# Application definition

INSTALLED_APPS = [
    "channels",  # Django Channels for WebSocket support
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
    "django_dramatiq",
    "dramatiq_crontab",
    "django_extensions",
    "django_vite",
    "django_htmx",
    "ninja",
    "widget_tweaks",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    "sbomify.apps.core",
    "sbomify.apps.teams",
    "sbomify.apps.sboms",
    "sbomify.apps.documents",
    "sbomify.apps.access_tokens",
    "sbomify.apps.billing",
    "sbomify.apps.notifications",
    "sbomify.apps.vulnerability_scanning",
    "sbomify.apps.onboarding",
    "sbomify.apps.compliance",
    "health_check",
    "health_check.db",
    "anymail",
    "sbomify.apps.licensing",
    "sbomify.apps.plugins",
    "sbomify.apps.tea",
    "sbomify.apps.controls",
    "sbomify.apps.oidc",
    "sbomify.apps.security_advisories",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Outer enough to see the final API response; copies the per-token throttle budget
    # stashed on the request onto X-RateLimit-* headers.
    "sbomify.apps.access_tokens.throttling.RateLimitHeadersMiddleware",
    "sbomify.apps.core.middleware.DynamicHostValidationMiddleware",
    "sbomify.apps.core.middleware.CustomDomainContextMiddleware",
    "sbomify.apps.core.middleware.RealIPMiddleware",
    "sbomify.apps.core.middleware.GzipRequestDecompressionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Must precede CsrfViewMiddleware so the bearer exemption flag is set before any
    # CSRF enforcement can run (Ninja's check_csrf and CsrfViewMiddleware both honour it).
    "sbomify.apps.core.middleware.BearerAuthCsrfExemptMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "sbomify.apps.core.middleware.HtmxMessagesMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "sbomify.apps.core.middleware.ContentSecurityPolicyMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

GZIP_REQUEST_MAX_SIZE = 200 * 1024 * 1024  # 200 MB – safety limit for decompressed request bodies

if REQUEST_TIMING_LOGGING_ENABLED:
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.middleware.common.CommonMiddleware") + 1,
        "sbomify.apps.core.middleware.RequestTimingLoggingMiddleware",
    )


if DEBUG:
    # Only add debug toolbar if it's available (dev dependencies installed)
    try:
        import debug_toolbar  # noqa: F401

        INSTALLED_APPS.append("debug_toolbar")
        MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")
    except ImportError:
        # Debug toolbar not available (e.g., in production with DEBUG=True)
        pass

    # Add CORS headers in development mode - allow all origins
    try:
        import corsheaders  # noqa: F401

        INSTALLED_APPS.append("corsheaders")
        MIDDLEWARE.insert(
            MIDDLEWARE.index("django.middleware.common.CommonMiddleware"),
            "corsheaders.middleware.CorsMiddleware",
        )
    except ImportError:
        pass

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = "sbomify.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "sbomify" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "sbomify.apps.core.context_processors.version_context",
                "sbomify.apps.core.context_processors.pending_invitations_context",
                "sbomify.apps.core.context_processors.pending_access_requests_context",
                "sbomify.apps.core.context_processors.global_modals_context",
                "sbomify.apps.core.context_processors.team_context",
                "sbomify.apps.core.context_processors.sentry_context",
                "sbomify.apps.core.context_processors.posthog_context",
            ],
        },
    },
]

WSGI_APPLICATION = "sbomify.wsgi.application"
ASGI_APPLICATION = "sbomify.asgi.application"


MESSAGE_TAGS = {
    messages.constants.DEBUG: "alert-info",
    messages.constants.INFO: "alert-info",
    messages.constants.SUCCESS: "alert-success",
    messages.constants.WARNING: "alert-warning",
    messages.constants.ERROR: "alert-danger",
}

# Filter out login success messages
MESSAGE_LEVEL = messages.constants.INFO  # Only show messages of INFO level and above


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "sbomify" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Enable WhiteNoise compression and proper headers for production
if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.ManifestStaticFilesStorage",
        },
    }

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# WhiteNoise configuration for better static file serving
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0  # 1 year cache for production

# Django Vite - now outputs to static/dist/ to avoid conflicts
USE_VITE_DEV_SERVER = os.environ.get("USE_VITE_DEV_SERVER", "False").lower() == "true"

if USE_VITE_DEV_SERVER:
    # Development mode - Vite dev server serves at /dist/
    # Note: Use localhost/127.0.0.1 for browser access, not Docker internal hostnames
    DJANGO_VITE = {
        "default": {
            "dev_mode": True,
            "dev_server_host": "127.0.0.1",  # Browser-accessible hostname
            "dev_server_port": int(os.environ.get("VITE_DEV_SERVER_PORT", "5170")),
            "static_url_prefix": "/dist/",
        }
    }
else:
    # Production mode - built assets are in static/dist/
    DJANGO_VITE = {
        "default": {
            "dev_mode": False,
            "manifest_path": str(BASE_DIR / "sbomify" / "static" / "dist" / "manifest.json"),
            "static_url_prefix": "dist/",
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Database


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": os.environ["SQL_ENGINE"],
#         "NAME": os.environ["SQL_DATABASE"],
#         "USER": os.environ["SQL_USER"],
#         "PASSWORD": os.environ["SQL_PASSWORD"],
#         "HOST": os.environ["SQL_HOST"],
#         "PORT": os.environ["SQL_PORT"],
#     }
# }

# DB_URL = os.environ.get("DATABASE_URL", "")
if "DATABASE_URL" in os.environ:
    db_config_dict = dj_database_url.parse(os.environ["DATABASE_URL"])
else:
    db_config_dict = {}
    DATABASE_USER = os.environ.get("DATABASE_USER", "")
    DATABASE_PASSWORD = os.environ.get("DATABASE_PASSWORD", "")
    DATABASE_NAME = os.environ.get("DATABASE_NAME", "")
    DATABASE_PORT = os.environ.get("DATABASE_PORT", "")

    if IN_DOCKER:
        DATABASE_HOST = os.environ.get("DOCKER_DATABASE_HOST", "")
    else:
        DATABASE_HOST = os.environ.get("DATABASE_HOST", "")

    db_config_dict = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DATABASE_NAME,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "HOST": DATABASE_HOST,
        "PORT": DATABASE_PORT,
    }

    _db_sslmode = os.environ.get("DATABASE_SSLMODE", "")
    if _db_sslmode:
        db_options: dict[str, str] = {"sslmode": _db_sslmode}
        _db_sslrootcert = os.environ.get("DATABASE_SSLROOTCERT", "")
        if _db_sslrootcert:
            db_options["sslrootcert"] = _db_sslrootcert
        db_config_dict["OPTIONS"] = db_options


DATABASES = {"default": db_config_dict}

# Redis Configuration
# REDIS_URL is the base connection URL (no database number, no query params):
#   redis://host:6379              (plain)
#   redis://:password@host:6379    (with password)
#   rediss://:password@host:6380   (TLS — note double 's')
# Database numbers are appended automatically below.
_redis_parsed = urlparse(os.environ.get("REDIS_URL", "redis://localhost:6379"))
if _redis_parsed.scheme not in ("redis", "rediss") or not _redis_parsed.netloc:
    raise ValueError("Invalid REDIS_URL: must start with redis:// or rediss:// and include a host")


def _sanitize_redis_netloc(netloc: str) -> str:
    """Redact credentials from netloc while preserving host/port and IPv6 brackets."""
    if "@" not in netloc:
        return netloc
    _, hostport = netloc.rsplit("@", 1)
    return f"****@{hostport}"


# Strip database number and query params — we manage DB numbers ourselves.
if _redis_parsed.path and _redis_parsed.path != "/":
    logging.warning(
        "REDIS_URL should not include a database number — stripped it. Use: %s://%s",
        _redis_parsed.scheme,
        _sanitize_redis_netloc(_redis_parsed.netloc),
    )
# Rebuild as clean base URL (scheme + auth + host:port only)
REDIS_URL = urlunparse((_redis_parsed.scheme, _redis_parsed.netloc, "", "", "", ""))

REDIS_CACHE_URL = f"{REDIS_URL}/0"  # Cache uses database 0
REDIS_WORKER_URL = f"{REDIS_URL}/1"  # Worker uses database 1
REDIS_CHANNELS_URL = f"{REDIS_URL}/2"  # WebSocket channels uses database 2

_redis_is_tls = _redis_parsed.scheme == "rediss"

# Optional custom CA certificate for Redis TLS connections.
# When unset, redis-py falls back to SSL_CERT_FILE / system trust store.
REDIS_CA_CERTS = os.environ.get("REDIS_CA_CERTS", "")
if REDIS_CA_CERTS and not _redis_is_tls:
    raise ValueError(
        "REDIS_CA_CERTS is set but REDIS_URL does not use TLS (rediss://). "
        "Either use rediss:// or remove REDIS_CA_CERTS."
    )

# Cache Configuration
CACHES: dict[str, dict[str, Any]]
if DEBUG:
    # Disable caching in development mode
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
else:
    # Use Redis cache in production
    _cache_pool_kwargs: dict[str, Any] = {"max_connections": 10}
    if REDIS_CA_CERTS:
        _cache_pool_kwargs["ssl_ca_certs"] = REDIS_CA_CERTS
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_CACHE_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "RETRY_ON_TIMEOUT": True,
                "CONNECTION_POOL_KWARGS": _cache_pool_kwargs,
            },
        }
    }

# Channel Layers for WebSocket support
_channels_host: str | dict[str, Any] = REDIS_CHANNELS_URL
if REDIS_CA_CERTS:
    _channels_host = {"address": REDIS_CHANNELS_URL, "ssl_ca_certs": REDIS_CA_CERTS}
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_channels_host],
            # Connection pool and timeout settings for production reliability
            "capacity": 1500,  # Maximum number of messages to store per channel
            "expiry": 60,  # Message expiry time in seconds
        },
    },
}

# Pass a pre-built client because Dramatiq's RedisBroker creates a
# ConnectionPool.from_url() that drops ssl_ca_certs kwargs.
_dramatiq_redis_options: dict[str, Any] = (
    {"client": redis.Redis.from_url(REDIS_WORKER_URL, ssl_ca_certs=REDIS_CA_CERTS)}
    if REDIS_CA_CERTS
    else {"url": REDIS_WORKER_URL}
)
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.redis.RedisBroker",
    "OPTIONS": _dramatiq_redis_options,
    "MIDDLEWARE": [
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "dramatiq.middleware.TimeLimit",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
    ],
}

DRAMATIQ_RESULT_BACKEND = {
    "BACKEND": "dramatiq.results.backends.redis.RedisBackend",
    "BACKEND_OPTIONS": _dramatiq_redis_options,
}

# Single-leader scheduling is enforced by `replicas: 1` on the
# `sbomify-scheduler` Compose service (and the equivalent in any prod
# orchestrator). We deliberately do NOT configure DRAMATIQ_CRONTAB.REDIS_URL
# because upstream `dramatiq-crontab` builds its Redis lock via
# `redis.Redis.from_url(url)` with no API for `ssl_ca_certs` — that fails
# SSL handshake against private-CA Redis (rediss:// + REDIS_CA_CERTS), which
# is how prod is deployed. Without REDIS_URL the package falls back to
# FakeLock; brief overlap during rolling deploys is safe because every
# scheduled actor is either idempotent (scans, purges, health checks) or
# has actor-level dedup (OnboardingEmail unique_together for drip emails).

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# WhiteNoiseMiddleware serves static files with a synchronous file iterator, and
# whitenoise 6.11 offers no async path (the middleware is not async_capable). Under
# ASGI, StreamingHttpResponse.__aiter__ therefore falls back to consuming it via
# sync_to_async and warns once per worker process.
#
# Harmless for static assets: the bytes are correct and the files are small. Note the
# fallback calls list() on the iterator, so the body is fully buffered rather than
# streamed -- fine for static assets, which are small.
#
# Be aware this is global, not scoped to WhiteNoise: Django raises the same message
# from StreamingHttpResponse.__aiter__ for any synchronous iterator under ASGI, so an
# application endpoint that streams a large response will have this warning hidden
# too, along with the buffering it is telling us about. Filtering cannot distinguish
# them -- the message is identical and the raising module is django.http.response
# either way. If we add real streaming endpoints, revisit this rather than assume the
# warning would have surfaced.
warnings.filterwarnings(
    "ignore",
    # Anchored at both ends and with the periods escaped, so this suppresses
    # exactly Django's message and nothing that merely begins with it. Note
    # Django has a sibling warning for the reverse case ("must consume
    # asynchronous iterators in order to serve them synchronously") which must
    # keep surfacing.
    message=(
        r"^StreamingHttpResponse must consume synchronous iterators in order to "
        r"serve them asynchronously\. Use an asynchronous iterator instead\.$"
    ),
    category=Warning,
)


# Logging config
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {"format": "%(asctime)s:%(name)s:%(levelname)s:%(message)s"},
    },
    "filters": {
        # Only known-benign exception types are suppressed to preserve observability.
        "suppress_shielded_future_errors": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: not is_benign_shielded_future_error(record),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "default",
        },
        "console_asyncio": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "default",
            "filters": ["suppress_shielded_future_errors"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "sbomify": {
            "handlers": ["console"],
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        # Surface dramatiq + dramatiq-crontab info logs (heartbeat, scheduler
        # liveness, actor execution). Without this, info-level logs from
        # those packages fall through to the WARNING root logger and are
        # silently dropped, making "did the cron actually fire?" hard to
        # diagnose from container logs alone.
        "dramatiq": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "sbomify.performance": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Token-auth audit trail (sbomify.audit.*). Pinned to INFO independent of
        # LOG_LEVEL so the success/expired events stay in the forensic record even
        # when the general log level is raised to WARNING.
        "sbomify.audit": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "core": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "allauth": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "allauth.socialaccount": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "asyncio": {
            "handlers": ["console_asyncio"],
            "level": "WARNING",
            "propagate": False,
        },
        # "teams": {
        #     "handlers": ["console"],
        #     "level": os.getenv("LOG_LEVEL", "INFO"),
        #     "propagate": False,
        # },
    },
}


# Feature flags
USE_KEYCLOAK = os.environ.get("USE_KEYCLOAK", "").lower() in ("true", "1", "yes")

# Authentication settings
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# AllAuth settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_LOGIN_ON_GET = True  # Auto-redirect to Keycloak on GET request to login
SOCIALACCOUNT_ADAPTER = "sbomify.apps.core.adapters.CustomSocialAccountAdapter"

# Modern AllAuth configuration
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_ADAPTER = "sbomify.apps.core.adapters.CustomAccountAdapter"

# Keycloak settings
KEYCLOAK_SERVER_URL = os.environ.get("KEYCLOAK_SERVER_URL", "http://keycloak:8080/")
KEYCLOAK_REALM = os.environ.get("KEYCLOAK_REALM", "sbomify")
KEYCLOAK_CLIENT_ID = os.environ.get("KEYCLOAK_CLIENT_ID", "sbomify")
KEYCLOAK_CLIENT_SECRET = os.environ.get("KEYCLOAK_CLIENT_SECRET", "")
KEYCLOAK_ADMIN_USERNAME = os.environ.get("KEYCLOAK_ADMIN_USERNAME", "admin")
KEYCLOAK_ADMIN_PASSWORD = os.environ.get("KEYCLOAK_ADMIN_PASSWORD", "admin")
KEYCLOAK_WEBHOOK_SECRET = os.environ.get("KEYCLOAK_WEBHOOK_SECRET", "")

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "keycloak",
                "name": "Keycloak",
                "client_id": KEYCLOAK_CLIENT_ID,
                "secret": KEYCLOAK_CLIENT_SECRET,
                "settings": {
                    "server_url": f"{KEYCLOAK_SERVER_URL}realms/{KEYCLOAK_REALM}/.well-known/openid-configuration",
                },
            }
        ]
    }
}

LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/login"

APP_BASE_URL = os.environ.get("APP_BASE_URL", "")
WEBSITE_BASE_URL = os.environ.get("WEBSITE_BASE_URL", APP_BASE_URL)
_trust_center_raw = os.environ.get("TRUST_CENTER_DOMAIN", "").strip()
TRUST_CENTER_DOMAIN = ""
if _trust_center_raw:
    _parsed_trust_center = urlparse(_trust_center_raw)
    # urlparse misparses bare "host:port" (e.g. "trustcenters.test:8000") as
    # scheme="trustcenters.test", so fall back to // prefix when hostname is None.
    if _parsed_trust_center.hostname is None:
        _parsed_trust_center = urlparse(f"//{_trust_center_raw}")
    # Use netloc to preserve port for local/dev usage (e.g. "trustcenters.test:8000").
    TRUST_CENTER_DOMAIN = _parsed_trust_center.netloc or _parsed_trust_center.hostname or ""

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False").lower() == "true"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@sbomify.com")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)  # For system-generated emails
EMAIL_SUBJECT_PREFIX = "[sbomify] "


logger = logging.getLogger(__name__)


def _sentry_traces_sampler(sampling_context: dict[str, Any]) -> float:
    """Sample traces for Sentry with fallback to default on invalid values."""
    try:
        base_rate = float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.1"))
    except (ValueError, TypeError):
        logger.warning("Invalid SENTRY_TRACES_SAMPLE_RATE, using default 0.1")
        base_rate = 0.1

    if base_rate <= 0:
        return 0.0

    try:
        api_rate = float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE_API", base_rate))
    except (ValueError, TypeError):
        api_rate = base_rate

    try:
        htmx_rate = float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE_HTMX", base_rate))
    except (ValueError, TypeError):
        htmx_rate = base_rate

    try:
        job_rate = float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE_JOBS", base_rate))
    except (ValueError, TypeError):
        job_rate = base_rate

    wsgi_environ = sampling_context.get("wsgi_environ")
    if wsgi_environ:
        path = wsgi_environ.get("PATH_INFO", "")
        if wsgi_environ.get("HTTP_HX_REQUEST"):
            return htmx_rate
        if path.startswith("/api/"):
            return api_rate
        return base_rate

    transaction_context = sampling_context.get("transaction_context") or {}
    op = transaction_context.get("op", "")
    if op.startswith("dramatiq") or op in ("queue.process", "task"):
        return job_rate

    return base_rate


_SENTRY_DSN = os.environ.get("SENTRY_DSN")

# With no DSN the SDK builds a client whose transport is None: every event is
# dropped silently and is_active() still returns True, so nothing surfaces the
# misconfiguration. Say so once at startup instead. Written to stderr directly
# because Django applies LOGGING later in django.setup(), so a logger call here
# would bypass the configured handlers and formatters.
if should_warn_missing_dsn(_SENTRY_DSN, debug=DEBUG):
    sys.stderr.write("SENTRY_DSN is not set - error reporting is disabled and all events will be discarded.\n")
    sys.stderr.flush()

sentry_sdk.init(
    dsn=_SENTRY_DSN,
    release=get_sbomify_version(),
    environment=resolve_environment(debug=DEBUG),
    integrations=[
        DjangoIntegration(),
        DramatiqIntegration(),
        LoggingIntegration(level=logging.INFO, event_level=logging.ERROR),
    ],
    traces_sampler=_sentry_traces_sampler,
    profiles_sample_rate=float(os.environ.get("SENTRY_PROFILES_SAMPLE_RATE", "0.1")),
    # CancelledError is expected under ASGI when clients disconnect mid-request.
    # On Python 3.14+ it's a BaseException that propagates through middleware.
    # ConnectionClosed (and its ConnectionClosedError/ConnectionClosedOK subclasses)
    # is expected when WebSocket clients disconnect (keepalive ping timeout, browser
    # tab closed, network change).
    ignore_errors=[asyncio.CancelledError, "websockets.exceptions.ConnectionClosed"],
)


# Workspaces app related config (legacy 'teams' app).
# The ``bot`` role is reserved for synthetic identities provisioned by
# OIDC Trusted Publishing bindings (see ``sbomify.apps.oidc``); it should
# NEVER appear in invite or role-change UIs presented to humans.
TEAMS_SUPPORTED_ROLES = [
    ("owner", "Owner"),
    ("admin", "Admin"),
    ("guest", "Guest"),
    ("bot", "Bot"),
]
# Invitation.role choices — subset of supported roles that can be
# stored on an Invitation row. Excludes only ``bot`` (reserved for
# OIDC synthetic identities, never invited). ``guest`` IS valid for
# Invitation because the trust-center auto-accept flow creates a
# guest-role Invitation when a user requests access — that row is
# accepted on login and upgrades the user to a guest Member.
# The InviteUserForm UI further excludes guest from its choices since
# admins shouldn't invite guests directly (they self-serve), but the
# model-level constraint stays permissive.
TEAMS_INVITABLE_ROLES = [(k, v) for k, v in TEAMS_SUPPORTED_ROLES if k != "bot"]
INVITATION_EXPIRY_DAYS = 7  # 7 days


JWT_ISSUER = os.environ.get("JWT_ISSUER", "sbomify")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", "HS256")
JWT_AUDIENCE = os.environ.get("JWT_AUDIENCE", "sbomify")

# Per-token API rate limit (#1060): a django-ninja "<count>/<period>" string applied
# per AccessToken pk. Generous enough for CI bursts while capping a leaked/runaway
# token; tighten via the env var. Effectively a no-op under DEBUG (DummyCache).
API_TOKEN_RATE_LIMIT = os.environ.get("API_TOKEN_RATE_LIMIT", "1000/min")

# Stricter per-token limit for expensive endpoints (artifact uploads), enforced
# alongside the global one (#1070). Lower because each call does real work (parse,
# S3 write, downstream scan/assessment enqueue).
API_TOKEN_HEAVY_RATE_LIMIT = os.environ.get("API_TOKEN_HEAVY_RATE_LIMIT", "100/min")

# Anonymous/session callers carry no token, so the per-token limits above never
# apply to them. Keyed per client IP. Generous enough that a human browsing the
# Trust Center never notices, low enough to blunt scripted enumeration.
API_ANONYMOUS_RATE_LIMIT = os.environ.get("API_ANONYMOUS_RATE_LIMIT", "120/min")

# OIDC Trusted Publishing — see sbomify.apps.oidc.
# Action workflows request an ID token with this audience; the backend
# enforces the ``aud`` claim against it during verification.
OIDC_GITHUB_ISSUER = os.environ.get("OIDC_GITHUB_ISSUER", "https://token.actions.githubusercontent.com")
OIDC_GITHUB_JWKS_URL = os.environ.get(
    "OIDC_GITHUB_JWKS_URL",
    "https://token.actions.githubusercontent.com/.well-known/jwks",
)
OIDC_GITHUB_AUDIENCE = os.environ.get("OIDC_GITHUB_AUDIENCE", "sbomify.com")
OIDC_TOKEN_TTL_SECONDS = int(os.environ.get("OIDC_TOKEN_TTL_SECONDS", "900"))  # 15 minutes
OIDC_JWKS_CACHE_SECONDS = int(os.environ.get("OIDC_JWKS_CACHE_SECONDS", "3600"))  # 1 hour
# Clock-skew tolerance (seconds) applied symmetrically to nbf/iat/exp when
# verifying GitHub OIDC tokens. GitHub's issuer clock can run a few seconds
# ahead of ours, so a freshly minted token's nbf/iat is often slightly in the
# future at verification time; with zero leeway PyJWT rejects it as "not yet
# valid" and every exchange fails. 60s matches common JWT clock-skew guidance.
OIDC_GITHUB_LEEWAY_SECONDS = int(os.environ.get("OIDC_GITHUB_LEEWAY_SECONDS", "60"))

# How stale AccessToken.last_used_at may be before an authenticated request
# refreshes it. Throttles the per-request write to one UPDATE per token per
# window so a token hammered in a tight loop doesn't write on every call. The
# field exists to spot stale/leaked tokens, so minute-level accuracy is enough.
# Clamped to >= 0: a negative value would invert the freshness window and make
# every request rewrite the field.
ACCESS_TOKEN_LAST_USED_THROTTLE_SECONDS = max(0, int(os.environ.get("ACCESS_TOKEN_LAST_USED_THROTTLE_SECONDS", "300")))

# Localstack and AWS/S3 related settings
AWS_REGION = os.environ.get("AWS_REGION", "")
AWS_ENDPOINT_URL_S3 = os.environ.get("AWS_ENDPOINT_URL_S3", "")

AWS_MEDIA_ACCESS_KEY_ID = os.environ.get("AWS_MEDIA_ACCESS_KEY_ID", "")
AWS_MEDIA_SECRET_ACCESS_KEY = os.environ.get("AWS_MEDIA_SECRET_ACCESS_KEY", "")
AWS_MEDIA_STORAGE_BUCKET_NAME = os.environ.get("AWS_MEDIA_STORAGE_BUCKET_NAME", "")
AWS_MEDIA_STORAGE_BUCKET_URL = os.environ.get("AWS_MEDIA_STORAGE_BUCKET_URL", "")

AWS_SBOMS_ACCESS_KEY_ID = os.environ.get("AWS_SBOMS_ACCESS_KEY_ID", "")
AWS_SBOMS_SECRET_ACCESS_KEY = os.environ.get("AWS_SBOMS_SECRET_ACCESS_KEY", "")
AWS_SBOMS_STORAGE_BUCKET_NAME = os.environ.get("AWS_SBOMS_STORAGE_BUCKET_NAME", "")
AWS_SBOMS_STORAGE_BUCKET_URL = os.environ.get("AWS_SBOMS_STORAGE_BUCKET_URL", "")

# Documents S3 settings - fallback to SBOMS bucket if not configured
AWS_DOCUMENTS_ACCESS_KEY_ID = os.environ.get("AWS_DOCUMENTS_ACCESS_KEY_ID", AWS_SBOMS_ACCESS_KEY_ID)
AWS_DOCUMENTS_SECRET_ACCESS_KEY = os.environ.get("AWS_DOCUMENTS_SECRET_ACCESS_KEY", AWS_SBOMS_SECRET_ACCESS_KEY)
AWS_DOCUMENTS_STORAGE_BUCKET_NAME = os.environ.get("AWS_DOCUMENTS_STORAGE_BUCKET_NAME", AWS_SBOMS_STORAGE_BUCKET_NAME)
AWS_DOCUMENTS_STORAGE_BUCKET_URL = os.environ.get("AWS_DOCUMENTS_STORAGE_BUCKET_URL", AWS_SBOMS_STORAGE_BUCKET_URL)

if DEBUG:
    # CSRF settings for development
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]

    # CORS settings - allow all origins in development mode
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    # Production cookie + transport hardening (#922). Caddy terminates TLS at the edge
    # (SECURE_PROXY_SSL_HEADER above lets Django see the original scheme), but Caddy
    # cannot set the Secure/SameSite attributes on Django-issued cookies — so we set them
    # here. (Tests relax these via test_settings; the HTTP test client can't use them.)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Session cookie stays "Lax" (NOT "Strict"): the Keycloak/OIDC login callback is a
    # cross-site top-level navigation, and a Strict session cookie would not be sent on
    # it, breaking the OAuth state handshake. The CSRF cookie can be Strict — it is read
    # by JS and only sent on same-site mutations.
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Strict"

    # Defense-in-depth behind Caddy's edge HTTP->HTTPS redirect. Exempt the internal
    # endpoints, which are probed over plain HTTP (container-to-container, no
    # X-Forwarded-Proto header): the Django health check, and the on-demand-TLS "ask"
    # endpoint Caddy hits to decide whether to issue a certificate for a custom/trust
    # center domain. A 301 here makes Caddy refuse the redirect and deny the cert.
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [r"^UuPha8mu/", r"^api/v1/internal/"]

    # HSTS (Caddy sets it at the edge too; harmless to assert at the app for direct hits).
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

STRIPE_API_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_SECRET_KEY = STRIPE_API_KEY
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_BILLING_URL = os.environ.get("STRIPE_BILLING_URL", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")

# Trial period settings
TRIAL_PERIOD_DAYS = int(os.environ.get("TRIAL_PERIOD_DAYS", "14"))
TRIAL_ENDING_NOTIFICATION_DAYS = int(os.environ.get("TRIAL_ENDING_NOTIFICATION_DAYS", "3"))

# Enable specific notification providers
NOTIFICATION_PROVIDERS = [
    "sbomify.apps.billing.notifications.get_notifications",
    "sbomify.apps.documents.notifications.get_notifications",
    "sbomify.apps.teams.notifications.get_notifications",
    "sbomify.apps.vulnerability_scanning.notifications.get_notifications",
]

# Optionally override refresh interval
NOTIFICATION_REFRESH_INTERVAL = 60 * 1000  # 1 minute

# Billing settings
BILLING = os.getenv("BILLING", "True").lower() == "true"

SITE_ID = 1

# Cloudflare Turnstile settings
TURNSTILE_SITE_KEY = os.environ.get("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY", "")

# Cloudflare DCV Delegation hostname for custom domain SSL
CLOUDFLARE_DCV_HOSTNAME = os.environ.get("CLOUDFLARE_DCV_HOSTNAME", "")

# Enterprise sales contact email
ENTERPRISE_SALES_EMAIL = os.environ.get("ENTERPRISE_SALES_EMAIL", "hello@sbomify.com")

# PostHog analytics
POSTHOG_API_KEY = os.environ.get("POSTHOG_API_KEY", "")
POSTHOG_HOST = os.environ.get("POSTHOG_HOST", "https://us.i.posthog.com")
